version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - 3306:3306
    volumes:
      - /Users/slugz/GenerationDE/Miniproject/Week5/mysql/database


